openapi: 3.0.3
info:
  title: "This is the auth API"
  version: 1.0.0
  description: "auth API"
paths:
  /v1/api/auth/login:
    post:
      tags:
        - Auth 
      summary: "User login"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthRequest'
      responses:
        '200':
          description: "login scuccess"
          content:
            application/json:
              schema:
                $ref : '#/components/schemas/AuthResponse'
        '401': 
          description: "username err or password err"
  /v1/api/auth/register:
    post: 
      tags: 
        - Auth
      summary: "User register"
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              $ref : '#/components/schemas/AuthRequest'
      responses:
        '201':
          description: "Register scuccess"
          content:
            application/json:
              schema: 
                $ref : '#/components/schemas/AuthResponse'
        '400':
          description: "User already exist"
components:
  schemas:
    AuthRequest:
      type: object
      required:
        - name 
        - password
      properties:
        name:
          type: string
          example: "looksaw"
          minLength: 3
          maxLength: 30
        password:
          type: string
          example : "123456"
          minLength: 8
          maxLength: 30
          format: password
    AuthResponse:
      type: object
      properties:
        token:
          type: string
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        userId:
          type: string
          example: "123"

  

