// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc_gen

import (
	"database/sql"
)

type Article struct {
	ID      int64          `json:"id"`
	Title   sql.NullString `json:"title"`
	Content sql.NullString `json:"content"`
	Preview sql.NullString `json:"preview"`
}

type ExchangeRate struct {
	ID           int64           `json:"id"`
	FromCurrency sql.NullString  `json:"from_currency"`
	ToCurrency   sql.NullString  `json:"to_currency"`
	Rate         sql.NullFloat64 `json:"rate"`
	Date         sql.NullTime    `json:"date"`
}

type User struct {
	ID       int64  `json:"id"`
	Name     string `json:"name"`
	Password string `json:"password"`
}
