// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc_gen

import (
	"context"
)

type Querier interface {
	CreateArticle(ctx context.Context, arg CreateArticleParams) (Article, error)
	CreateExchangeRate(ctx context.Context, arg CreateExchangeRateParams) (ExchangeRate, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteARticle(ctx context.Context, id int64) error
	DeleteUserByID(ctx context.Context, userID int64) error
	DeleteUserByName(ctx context.Context, uesrName string) error
	GetArticleByID(ctx context.Context, id int64) (Article, error)
	GetArticleList(ctx context.Context) ([]Article, error)
	GetExchangeRateByID(ctx context.Context, id int64) (ExchangeRate, error)
	GetExchangeRateList(ctx context.Context) ([]ExchangeRate, error)
	GetUserByID(ctx context.Context, userID int64) (User, error)
	GetUserByName(ctx context.Context, userName string) (User, error)
	GetUserList(ctx context.Context) ([]User, error)
	GetUserWithRange(ctx context.Context, arg GetUserWithRangeParams) ([]User, error)
	UpdateArticle(ctx context.Context, arg UpdateArticleParams) (Article, error)
	UpdateUserById(ctx context.Context, arg UpdateUserByIdParams) (User, error)
	UpdateUserByName(ctx context.Context, arg UpdateUserByNameParams) (User, error)
}

var _ Querier = (*Queries)(nil)
